plugins {
    id 'com.android.application'
}

android {
    compileSdk {
        version = release(37) {
            minorApiLevel = 1
        }
    }
    buildToolsVersion "36.1.0"

    def releaseVersionCode = providers.gradleProperty("releaseVersionCode").orNull
    def releaseVersionName = providers.gradleProperty("releaseVersionName").orNull

    defaultConfig {
        applicationId "io.github.lsposed.disableflagsecure"
        minSdkVersion 31
        targetSdkVersion 37
        versionCode releaseVersionCode != null ? Integer.parseInt(releaseVersionCode) : rootProject.ext.commitCount
        versionName releaseVersionName ?: "5.0.1"
    }

    Properties localProperties = new Properties()
    if (project.rootProject.file('local.properties').exists()) {
        localProperties.load(project.rootProject.file('local.properties').newDataInputStream())
    }

    def storeFilePath = System.getenv("RELEASE_STORE_FILE") ?: localProperties.getProperty("storeFile")
    def storePasswordValue = System.getenv("RELEASE_STORE_PASSWORD") ?: localProperties.getProperty("storePassword")
    def keyAliasValue = System.getenv("RELEASE_KEY_ALIAS") ?: localProperties.getProperty("keyAlias")
    def keyPasswordValue = System.getenv("RELEASE_KEY_PASSWORD") ?: localProperties.getProperty("keyPassword")

    signingConfigs {
        if (storeFilePath != null) {
            config {
                storeFile project.rootProject.file(storeFilePath)
                storePassword storePasswordValue
                keyAlias keyAliasValue
                keyPassword keyPasswordValue
            }
        }
    }

    buildTypes {
        configureEach {
            vcsInfo.include false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            if (storeFilePath != null) {
                signingConfig signingConfigs.config
            }
        }
        release {
            if (storeFilePath != null) {
                signingConfig signingConfigs.config
            } else {
                signingConfig signingConfigs.debug
            }
            vcsInfo.include false
            minifyEnabled true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    lint {
        checkReleaseBuilds false
    }

    dependenciesInfo.includeInApk false
    enableKotlin = false
    namespace 'io.github.lsposed.disableflagsecure'
}

dependencies {
    compileOnly 'androidx.annotation:annotation:1.10.0'
    compileOnly 'io.github.libxposed:api:102.0.0'
}
